# -*- coding: utf-8 -*-
"""DS_INSIGHTS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DUnDjHrERePKwZodIQ61q-6xvA7bdUyy
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/ds_salaries.csv')
df.head()

df.isnull().sum()

column_names = df.columns.tolist()
print("Column Names: ", column_names)

"""Average Salaries by Experience Level"""

# calculate the average salaries by experience level
avg_salary = df.groupby('experience_level')['salary_in_usd'].mean()

# plot the bar chart
plt.bar(avg_salary.index, avg_salary.values)
plt.title('Average Salaries by Experience Level')
plt.xlabel('Experience Level')
plt.ylabel('Salary (USD)')
plt.show()
# save the plot as PNG file
plt.savefig('GRAPH_1.png')

"""Average Salaries by Company Size"""

# calculate the average salaries by company size
avg_salary = df.groupby('company_size')['salary_in_usd'].mean()

# plot the line chart
plt.plot(avg_salary.index, avg_salary.values)
plt.title('Average Salaries by Company Size')
plt.xlabel('Company Size')
plt.ylabel('Salary (USD)')
plt.show()
# save the plot as PNG file
plt.savefig('GRAPH_2.png')

"""Top Paid Data Science Job"""

df['salary_in_usd'].groupby(df['job_title']).sum().nlargest(10).plot.bar(color= 'b')
# save the plot as PNG file
plt.savefig('GRAPH_3.png')

"""Average Data Science Jobs Salaries by year"""

# calculate the average salaries by year
avg_salary = df.groupby('work_year')['salary_in_usd'].mean()

# create a list of colors for the bars
colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']

# create a list of x positions for the bars
x_pos = np.arange(len(avg_salary.index))

# plot the bar chart
plt.bar(x_pos, avg_salary.values, color=colors)

# add labels and title to the plot
plt.title('Average Data Science Jobs Salaries by Year')
plt.xlabel('Year')
plt.ylabel('Salary (USD)')

# add x-tick labels
plt.xticks(x_pos, avg_salary.index)

plt.show()
# save the plot as PNG file
plt.savefig('GRAPH_4.png')

"""Salary vs. Years of Experience"""

# plot the scatter plot
plt.scatter(df['work_year'], df['salary_in_usd'])
plt.title('Salary vs. Years of Experience')
plt.xlabel('Years of Experience')
plt.ylabel('Salary (USD)')
plt.show()
# save the plot as PNG file
plt.savefig('GRAPH_5.png')

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
import pandas as pd

# calculate the average salaries by experience level
avg_salary1 = df.groupby('experience_level')['salary_in_usd'].mean()

# calculate the average salaries by company size
avg_salary2 = df.groupby('company_size')['salary_in_usd'].mean()

# calculate the sum of salaries by job title
top_jobs = df['salary_in_usd'].groupby(df['job_title']).sum().nlargest(10)

# calculate the average salaries by year
avg_salary3 = df.groupby('work_year')['salary_in_usd'].mean()

# create a list of colors for the bars
colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']



# create the grid layout
fig = plt.figure(figsize=(12, 10))
grid = gridspec.GridSpec(ncols=3, nrows=2, figure=fig)

# create the first graph and add it to the grid layout
ax1 = fig.add_subplot(grid[0, :2])
avg_salary = df.groupby('experience_level')['salary_in_usd'].mean()
ax1.bar(avg_salary.index, avg_salary.values)
ax1.set_title('Average Salaries by Experience Level')
ax1.set_xlabel('Experience Level')
ax1.set_ylabel('Salary (USD)')

# create the second graph and add it to the grid layout
ax2 = fig.add_subplot(grid[0, 2])
avg_salary = df.groupby('company_size')['salary_in_usd'].mean()
ax2.plot(avg_salary.index, avg_salary.values)
ax2.set_title('Average Salaries by Company Size')
ax2.set_xlabel('Company Size')
ax2.set_ylabel('Salary (USD)')

# create the third graph and add it to the grid layout
ax3 = fig.add_subplot(grid[1, 0])
df['salary_in_usd'].groupby(df['job_title']).sum().nlargest(10).plot.bar(color= 'b', ax=ax3)
ax3.set_title('Top 10 Salaries by Job Title')
ax3.set_xlabel('Job Title')
ax3.set_ylabel('Salary (USD)')

# create the fourth graph and add it to the grid layout
ax4 = fig.add_subplot(grid[1, 1])
avg_salary = df.groupby('work_year')['salary_in_usd'].mean()
colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']
x_pos = np.arange(len(avg_salary.index))
ax4.bar(x_pos, avg_salary.values, color=colors)
ax4.set_title('Average Salaries by Year')
ax4.set_xlabel('Year')
ax4.set_ylabel('Salary (USD)')
ax4.set_xticks(x_pos)
ax4.set_xticklabels(avg_salary.index)

# create the fifth graph and add it to the grid layout
ax5 = fig.add_subplot(grid[1, 2])
ax5.scatter(df['work_year'], df['salary_in_usd'])
ax5.set_title('Salary vs. Years of Experience')
ax5.set_xlabel('Years of Experience')
ax5.set_ylabel('Salary (USD)')

# adjust the layout
fig.tight_layout()

# save the plot as PNG file
plt.savefig('dashboard.png')
plt.show()