# -*- coding: utf-8 -*-
"""DS_INSIGHTS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DUnDjHrERePKwZodIQ61q-6xvA7bdUyy
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/ds_salaries.csv')
df.head()

df.isnull().sum()

column_names = df.columns.tolist()
print("Column Names: ", column_names)

"""Average Salaries by Experience Level"""

# calculate the average salaries by experience level
avg_salary = df.groupby('experience_level')['salary_in_usd'].mean()

# plot the bar chart
plt.bar(avg_salary.index, avg_salary.values)
plt.title('Average Salaries by Experience Level')
plt.xlabel('Experience Level')
plt.ylabel('Salary (USD)')
plt.show()
# save the plot as PNG file
plt.savefig('GRAPH_1.png')

"""Average Salaries by Company Size"""

# calculate the average salaries by company size
avg_salary = df.groupby('company_size')['salary_in_usd'].mean()

# plot the line chart
plt.plot(avg_salary.index, avg_salary.values)
plt.title('Average Salaries by Company Size')
plt.xlabel('Company Size')
plt.ylabel('Salary (USD)')
plt.show()
# save the plot as PNG file
plt.savefig('GRAPH_2.png')

"""Top Paid Data Science Job"""

df['salary_in_usd'].groupby(df['job_title']).sum().nlargest(10).plot.bar(color= 'b')
# save the plot as PNG file
plt.savefig('GRAPH_3.png')

"""Average Data Science Jobs Salaries by year"""

# calculate the average salaries by year
avg_salary = df.groupby('work_year')['salary_in_usd'].mean()

# create a list of colors for the bars
colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']

# create a list of x positions for the bars
x_pos = np.arange(len(avg_salary.index))

# plot the bar chart
plt.bar(x_pos, avg_salary.values, color=colors)

# add labels and title to the plot
plt.title('Average Data Science Jobs Salaries by Year')
plt.xlabel('Year')
plt.ylabel('Salary (USD)')

# add x-tick labels
plt.xticks(x_pos, avg_salary.index)

plt.show()
# save the plot as PNG file
plt.savefig('GRAPH_4.png')

"""Salary vs. Years of Experience"""

# plot the scatter plot
plt.scatter(df['work_year'], df['salary_in_usd'])
plt.title('Salary vs. Years of Experience')
plt.xlabel('Years of Experience')
plt.ylabel('Salary (USD)')
plt.show()
# save the plot as PNG file
plt.savefig('GRAPH_5.png')